### PR TITLE
remove bullets from data-bullet-style:none lists

### PR DESCRIPTION
**Pull request by ajluk**
Issue: #1729

### CODE REVIEW

**Comment by Stackblocks** [comment]
When I regenerate the book using this branch I still get the bulleted list in Appendix C, so it may need some additional work.

image

**Comment by ajluk** [comment]
@Stackblocks it is awkward but I have checked it again today (bake and build pdf on this branch) and it looks fine. Could you check again?:
image

**Comment by Stackblocks** [comment]
@ajluk You're right! it looks like it was an issue on my end. Thanks for double checking, i'm glad nothing else has to be done. 🎉 

image

**Comment by ajluk** [comment]
Changes in TDS: 
New Component needs to be added in **BasicTableShape** under the **TableDataList** (l.194):
**TableDataUnstyledList**
properties:
list-style-type: none,

**Pull request merged**
