### PR TITLE
Add contemporary math to the corn theme

### PR DESCRIPTION
**Pull request by KarinaMendez2**
for: #3801

Currently working:

General things:
- [ ] Table of Contents - Documentation #2060 / Working card: #3804
- [ ] Splash image - Documentation #1752 / Working card: #3806
- [ ]  Figure and table caption/title/number styling - Documentation #2185 / Working card: #3807
- [ ]  Headers - Documentation #2144 / Working card: #3805
- [ ]  Chapter Outline & Introduction - Documentation #2189 / Working card: #3817
- [ ]  Learning Objectives - Documentation #2190 / Working card: #3818
- [ ]  Tables - Documentation #2204 / Working card: #3819
- [ ] Examples with titles - Documentation #2209 / Working card #3821
- [ ] Verify that exercises are pulled in from exercises.openstax.org (are there exercises or are there errors)

Feature-like things:

- [ ] no class notes - Definition & Formulas - Documentation #2191 / Working Card #3820
- [ ]  Work It Out - Documentation #2256 / Working Card #3830
- [ ]  no class notes - Definition & Formulas - Documentation #2191 / Working Card #3820 
- [ ] Who Knew - Documentation #2200 / Working Card #3827 
- [ ] Work It Out - Documentation #2256 / Working Card #3830 
- [ ] Tech Check - Documentation #2208 / Working Card #3828 
- [ ] People in Mathematics - Documentatioin #2208 / Working card #3826 
- [ ] Your Turn - Documentation #2200 / Working card #3823 
- [ ] Video - Documentation #2206 / Working card #3824 
- [ ] Traffic Light - Documentation #2179 / Working caard: #3825

End of Chapter Content

- [ ]  Key Terms - #3832
- [ ]  Key Concepts - also in #3832
- [ ]  Videos - also in #3832
- [ ]  Formulas - also in #3832
- [ ]  Projects - #3860
- [ ]  Chapter Review - included in #3860
- [ ]  Chapter Test - included in #3860

End of Book Content

 NO APPENDICES

- [ ] Answer Key - Working Card #3833
- [ ]  Index - Documentation #2428 / Working Card #3834

### CODE REVIEW

**Comment by brittany-johnson** [comment]
Looking good! Generated it locally as well, didn't see any issues. 
I won't approve yet since it seems like this PR is a draft and you still have stuff to add? So you can ping me when you're ready for a final review.

**Review by kswanson33 — COMMENTED** [review]
One small comment, & not sure why the concourse build is failing (my login credentials seem to have stopped working so I can't check 🙃 ) but typically if the branch build is passing, the concourse build is also fine. Maybe try running it again?

Otherwise, this is looking really good! Congrats on styling your first book 🎉

**Comment by lwtchu** [comment]
Request review and then merge into lovely.london

**Comment by kswanson33** [comment]
The error message on Travis is complaining about a difference in the generated recipe vs. the recipe file that's in this commit.

image

See if this passes after recipes are regenerated! Otherwise, you can see what's going wrong with the build by clicking "Details" next to the failed check and then clicking "The build". Alternatively, run `./scripts/test` locally. Checks should pass before this gets merged.

**Review by kswanson33 — APPROVED** [review]

**Review by brittany-johnson — APPROVED** [review]

**Review by LostMojo — APPROVED** [review]

**Pull request merged**
