### PR TITLE
[WIP] Issue 2114

### PR DESCRIPTION
**Pull request by brittany-johnson**
https://github.com/openstax/cnx-recipes/issues/2114

### CODE REVIEW

**Comment by wilkus27** [comment]
@brittany-johnson I found out why it doesn't work.

This is how footnotes looks like in baked html:
image

This text is inside tag `aside[role="role-docfootnote"]` and for this tag we applied property `float: footnote`. So in this case Prince moves tag to the end of page and instead creates footnote call in this place (which we remove in styles by `content: none` property).

And theoretically it's working:

image

Footnote is at the same page as footnote call, but this one created by Prince, not our in `a[role="doc-noteref"]`.

**Comment by brittany-johnson** [comment]
It took some time for me to be able to work on this again, sorry for the delay! 

As a test I removed the `content: none` from `aside[role="doc-footnote"]::footnote-call` and added `prince-footnote-policy: keep-with-line` to `div.os-note-body > p`. The result is the screenshot below. 

I see what you mean that Prince is still making a place for the footnote that we moved with `float: footnote`, but Prince's footnote and our footnote are both on the following page instead of the page where the call occurs. 

Screen Shot 2020-05-19 at 3 42 57 PM

**Comment by wilkus27** [comment]
@brittany-johnson on the first screenshot this `1` at the bottom of the note is not a place for the footnote that we moved with `float`, it is a footnote call automatically created by Prince. So it's working as intendent - footnote call is on the same page as footnote marker. 

Here is how prince is working: (https://www.princexml.com/doc/footnotes/#footnotes).

image

This blue `1` on your screenshot it is a footnote call `hard coded` by us, we create it by recipes.

**Comment by wilkus27** [comment]
This is our markup in baked html:

image

So when we apply `float: footnote` for `aside` and run Prince, it moves `aside` to the end of the PDF page and creates in this place footnote call. Prince ignores `a[role=doc-noteref]` because it treats it as regular element, not part of the footnote.

**Comment by wilkus27** [comment]
If we want to use all footnotes properties dedicated by Prince `aside` should be in text next to the `a[role=doc-noteref]`. Then footnote call created by Prince will be at the same place as footnote call hard coded by us. But it requires additional work in Rex :disappointed: Another solution could be do not allow page breaks inside notes, but then there is a lot of empty spaces in the PDF.

**Comment by brittany-johnson** [comment]
@wilkus27 I suspected we would need a recipe change but I was hoping with all of my heart we somehow wouldn't LOL!! 

I will move this to the icebox until the current footnote work is at least on production. 

Thank you so much again Natalia for investigating this with me!!

**Comment by MartaSztuka** [comment]
##### PASSED

**Pull request closed without merging**
