### PR TITLE
Fix AddMan Exercise Selectors

### PR DESCRIPTION
**Pull request by Stackblocks**
I missed these when initially setting up AddMan, so the build-styles script currently breaks when run. This fix should resolve that.

### CODE REVIEW

**Review by ajluk — CHANGES_REQUESTED** [review]
@Stackblocks The styles should be regenerated as well, because the selectors weren't added in the `pdf-css` file before. Now the PR have no conflicts, so you should do it before merging.

**Comment by Stackblocks** [comment]
@ajluk I ran `./script/run ./script/build-styles` and there were no changes as a result. Am I missing another component of this construction outside of the `_exercises-settings.scss` file?

**Comment by brittany-johnson** [comment]
Try running `PLATFORM="pdf" node ./styles/build/build.js  styles/books/additive-manufacturing/book.scss ./styles/output/additive-manufacturing-pdf.css`. That generated an output for me

**Review by brittany-johnson — CHANGES_REQUESTED** [review]
left comment

**Comment by Stackblocks** [comment]
Using the alternative script worked! I've pushed a second commit containing the updated style files.

**Comment by ajluk** [comment]
@Stackblocks I'm not sure why the general script wouldn't  work for this book on your machine locally. I have never met such errors, but  I'm glad the other script for one book worked! Everything looks good!

**Review by ajluk — APPROVED** [review]

**Review by brittany-johnson — APPROVED** [review]

**Pull request merged**
