### PR TITLE
Revert "Change script/fetch-html to not use ssh (#983)"

### PR DESCRIPTION
**Pull request by karenc**
This is part of the baked pdf CLI modification to `./script/fetch-html`.
We are removing this from master and putting all the baked pdf CLI stuff
in its own branch.

---

The new non-ssh way [doesn't work on some of the Katalyst books](https://github.com/openstax/cnx/issues/350).
So we need to be able to run the old scripts on master.

### CODE REVIEW

**Comment by karenc** [comment]
The baked pdf CLI stuff is in a new branch called `cli-master`.

**Comment by tomjw64** [comment]
:cry: Sad to see these go away temporarily. Really liked the changes

**Comment by karenc** [comment]
@tomjw64 Aw, thanks for your support!!!  I guess we should've tested the script with the katalyst books :woman_facepalming: :sweat_smile:

**Comment by karenc** [comment]
I just rebased this so it's ready to be merged.

**Comment by BryanEliDimas** [comment]
With everyone's blessing... I'm going to merge.

**Pull request merged**
