### PR TITLE
Clean up answer key

### PR DESCRIPTION
**Pull request by wilkus27**
Issue: https://github.com/openstax/cnx-recipes/issues/1309

### CODE REVIEW

**Comment by wilkus27** [comment]
This is how it displays locally:

image

I'm not sure about subtitles. Are they styled correctly? 

In document https://drive.google.com/file/d/1t89_ljHdJA7bTx6lRix5wh1fNE7XSBzH/view `Chapter #` is smaller and not all caps:

image

Should style of this subtitle be based on this document or on https://github.com/openstax/cnx-recipes/issues/1072? 

There we can find such information about headers:

image

**Comment by wilkus27** [comment]
After ran `build-styles` script there are no changes in other files. I checked, `use('AnswerKey', 'carnival:::AnswerKeyShape')` is not included in book.scss for Anatomy and Biology. Should I add this?

**Comment by brittweinstein** [comment]
@wilkus27 can we merge this and move it to testing?

**Comment by wilkus27** [comment]
@brittweinstein Yes, I wasn't sure about color of font, but after discussion with Helene, inconsistencies will be fixed later. At this moment it is good as is. So I'm going to merge this PR.

**Pull request merged**
