### PR TITLE
Algebra and trigonometry: linebreak in vectors

### PR DESCRIPTION
**Pull request by KarinaMendez2**
for: https://github.com/openstax/cnx-recipes/issues/3855

### CODE REVIEW

**Comment by ajluk** [comment]
@KarinaMendez2 I have checked if the change you made will break the styling of `p` titles in exercises becuase they utilize the same selector and it's not :relaxed: Here are the titles that utilize also the same selector:
image

Also please remember to regenerate the styles for all the books within the general script: `./script/run ./script/build-styles`, because right now in your PR only styles for Precalculus has been generated and the change also concerns the other math (corn theme) books. 

@lwtchu This problem occurred again because the markup has been changed on production in Algebra Trigonometry - attribute `[data-effect="bold"]` has been added to `strong` tag: 
image
and this selector is also used for exercise paragraph titles in Prealgebra (`p > [data-effect="bold"]`) which are set to display as block elements (starting on new line): 
image

Here is how the same paragraph as shown in the issue decription looked before in Precalculus (I have checked the old content form A&T as well): 
image

**Review by ajluk — COMMENTED** [review]
@KarinaMendez2 Looks good!  I have only left a comment with some explanation why this issue occurred again  with a friendly reminder to regenerate all css styles for all the books and also please remember to change the base branch to `j.j`

**Comment by lwtchu** [comment]
adding a note here - does the `data-effect="bold"` cause problems in general? i think it's because whoever marked up the content initially put `<emphasis effect="bold">` which is redundant and not accurate so wondering if we should remove it in the content 🤔  or this fix will fix it regardless

**Comment by ajluk** [comment]
@lwtchu the `data-effect="bold"` attribute is only problematic because it is a part of the selector by which we select the exercise paragraph titles: `p > [data-effect="bold"]`  and whenever in exercises this title is used (it is present in all of the column shapes) it will override other paragraphs with a child with this attribute (`data-effect="bold`).

**Comment by lwtchu** [comment]
@ajluk ah okay i willl...still ask since it seems redundant for it to have a attribute like that on it

**Review by ajluk — APPROVED** [review]

**Pull request merged**
