### PR TITLE
Add style to module headers in anatomy

### PR DESCRIPTION
**Pull request by wilkus27**
Issue https://github.com/openstax/cnx-recipes/issues/1396

### CODE REVIEW

**Comment by wilkus27** [comment]
In this case I move settings to `book.scc` files. 

@tomjw64 I was also trying to use `create_subshape` mixin, as you advised me, but this solution is good when we want to change the explicit value. It doesn't work when value is a map.

image (10)

**Comment by tomjw64** [comment]
@wilkus27 was your `use` statement before your settings? It's hard to tell what went wrong without seeing the code

**Comment by wilkus27** [comment]
@tomjw64 I included `create_subshape` once in `module-settings` file, another time in `module-shapes` file. In each case in output file I get implicit value `color: (_ref: "colorMap:::anatomyHeaderColor"),`. I will try to push such changes in another PR. It will be easier to find cause of this.

**Comment by wilkus27** [comment]
I try this here: https://github.com/openstax/cnx-recipes/pull/1399/commits/795336381f3dc1d25d7763291ad236ce1b575759

**Pull request merged**
