### PR TITLE
changed the numbering of links to examples

### PR DESCRIPTION
**Pull request by Adrianltd**
https://github.com/openstax/cnx-recipes/issues/993

### CODE REVIEW

**Comment by Adrianltd** [comment]
@tomjw64 According to the tests (https://github.com/openstax/cnx-recipes/issues/993#issuecomment-480885724) numbering is consistent. 
The Precalculus books have different kind of numbering than other books (everything is numbered with reset at module and the numbering does not take chapters into consideration so for example it's `5` instead of `1.5`).

Ping me of it's good to merge.

**Comment by tomjw64** [comment]
@Adrianltd My concern was that the verification test was not complete in that it did not check the numbering on examples in any chapters/modules after Chapter 1 - module 1. Your changes do not imply that the examples now reset every module.

**Comment by Adrianltd** [comment]
@tomjw64 you were right, after retesting it came out that the examples did not reset properly. It's not assosiated with this PR, but good catch. I'll fix it and let you know when it's ready.

**Comment by Adrianltd** [comment]
@tomjw64 after few tests it turned out that it was associated with this PR, not the unproper reset of examples' numbering. They did reset at correct places - examples had proper numbering, but the numbering of the links didn't use the proper count-mixin and counter name.
Now it should be good, tested locally and looks fine. QA will verify tomorrow.

Thank you once again for your good eye!

**Pull request merged**
