### PR TITLE
Rename cssselect2 to cnx-cssselect2

### PR DESCRIPTION
**Pull request by pumazi**
See also https://github.com/openstax/cnx-cssselect2/pull/9

### CODE REVIEW

**Comment by openstaxalina** [comment]
@pumazi could you advise on a test plan for this?

**Comment by helenemccarron** [comment]
@pumazi I run into this error when I try to run `./scripts/setup` (it was pre-existing)
```
Obtaining cnx-cssselect2 from git+https://github.com/openstax/cnx-cssselect2.git@master#egg=cnx-cssselect2 (from -r ./requirements.txt (line 4))
  Updating ./venv/src/cnx-cssselect2 clone (to revision master#egg=cnx-cssselect2)
  Did not find branch or tag 'master#egg=cnx-cssselect2', assuming revision or ref.
fatal: ambiguous argument 'master#egg=cnx-cssselect2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Command "git reset --hard -q master#egg=cnx-cssselect2" failed with error code 128 in /Users/helene/openstax/cnx-recipes/venv/src/cnx-cssselect2
./script/setup: ERROR: could not run [pip install -r ./requirements.txt] ```

**Comment by pumazi** [comment]
Looks like I'll need to update this PR. @helenemccarron, please feel free to poke me about this. I'll get this on the top of my queue.

**Comment by pumazi** [comment]
@helenemccarron are you experiencing this error when trying to run this branch?

I'm not really able to run that script myself, because well, it install the universe onto my machine. No offense, but I don't really want the universe on my machine.

**Comment by helenemccarron** [comment]
Yes, I know 👽 Yes, it does. It does on master as well.

**Comment by helenemccarron** [comment]
uhm, pushed by mistake >.<

**Comment by pumazi** [comment]
The good news is I've managed to run `./script/setup` via the `Dockerfile` commited in #874.

The end result looks good:

```
root@adc8997bdaa3:/repos/cnx-recipes# venv/bin/pip freeze
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
atomicwrites==1.3.0
attrs==18.2.0
certifi==2018.11.29
chardet==3.0.4
-e git+https://github.com/openstax/cnx-cssselect2.git@e75af7659b2de3e7b9f71a7fd1c8265e69a1532c#egg=cnx_cssselect2
-e git+https://github.com/Connexions/cnx-easybake.git@b4d399c28d21dc144b2067e0f0fd7537b530295c#egg=cnx_easybake
-e git+https://github.com/Connexions/cnx-epub.git@9a23a4a6e0fbd52a3a229ff5e9cfcddee6c6bbee#egg=cnx_epub
cssselect==1.0.3
funcsigs==1.0.2
idna==2.8
Jinja2==2.10
lxml==4.3.1
MarkupSafe==1.1.0
more-itertools==5.0.0
pathlib2==2.3.3
pluggy==0.8.1
py==1.7.0
PyICU==1.9.8
pytest==4.3.0
python-memcached==1.59
requests==2.21.0
scandir==1.9.0
six==1.12.0
tinycss2==0.6.1
urllib3==1.24.1
webencodings==0.5.1
```

**Comment by pumazi** [comment]
As a side note, using the released version rather than pulling in the tip of master is going to protect you from problems happening with changes on the tip of master. That protects you from being blocked and the other developers making the changes on that package. pyup.io is our friend!

**Comment by brittweinstein** [comment]
@pumazi is this complete? should we close/move to review or testing?

**Comment by helenemccarron** [comment]
@pumazi, so this will work only with the `Dockerfile`?  Should we prepare ourselves to reinstall recipes via Docker?

**Comment by pumazi** [comment]
This looks to now have been taken care of by pinning against the released version of cnx-easybake. So no longer a valid PR.

**Pull request closed without merging**
