### PR TITLE
enable toc-eoc-composite-chapter flag microbiology

### PR DESCRIPTION
**Pull request by ajluk**
Issue: #1692

### CODE REVIEW

**Comment by brittany-johnson** [comment]
Everything looks good but requirements may have changed. I left a comment in the issue here: 
https://github.com/openstax/cnx-recipes/issues/1692

**Comment by ajluk** [comment]
@brittany-johnson can I apply changes to ToC including changed requirements about design within this PR?

**Comment by ajluk** [comment]
I have added changes due to the new requirements to just keep the main section (not the nested one) in the ToC.

**Comment by brittweinstein** [comment]
@ajluk I think this is ready to be merged!

**Pull request merged**
