### PR TITLE
Numbered list in abstract

### PR DESCRIPTION
**Pull request by wilkus27**
https://github.com/openstax/cnx-recipes/issues/888 Change bullet list in abstract to list with three level numbering: #chapter.#section.#item

### CODE REVIEW

**Comment by wilkus27** [comment]
Now lists look like that:

abstract

Automatic list numbering will be removed by webview.

**Comment by wilkus27** [comment]
@helenemccarron I tried to modify existing mixin related with custom lists. Those changes rebuild output in dev-math and chemistry. Should I apply release flag in that case? 

About calculus, at this moment those changes don't work there, because list in abstract should be `<ol>` not `<ul>`. Do we want to do this modification in content or should I create some mixin in recipe, which do this change?

**Comment by MartaSztuka** [comment]
Issue is fixed
Screenshot from 2019-03-29 14-37-08
Screenshot from 2019-03-29 14-38-37
Screenshot from 2019-03-29 14-39-11

**Comment by wilkus27** [comment]
@helenemccarron in a139ec5 I was trying to reduce repeating code as we discussed before. Please, give me your thoughts about it.

**Comment by brittany-johnson** [comment]
@wilkus27 Hey! This looks really good! 
We suggest using one selector, instead of an `if else` for `className` and `dataTypeName` and to package this with a release flag

**Comment by wilkus27** [comment]
@brittany-johnson To be sure, you mean to use one variable called `selector` inside the `$Config_CustomList`, so in calculus it will be:
```
$Config_CustomList: (
  (selector: '[data-type="abstract"] ul', beforeLabel: counter(chapter) "." counter(section) ".", afterLabel: ". "),
);
```
and in dev-math it will be:
```
$Config_CustomList: (
  (selector: '.stepwise', beforeLabel: "Step ", afterLabel: ". "),
);
```
that's right? If yes, with such solution there is a problem with that part of code:
```
#{$selector} {
        counter-reset: #{$counterName};
        class: os-#{$name};
        > li {
          &::inside {
            container: span;
            class: "os-#{$name}-content";
          }
          &::before {
            container: span;
            class: "os-#{$name}-token";
            counter-increment: #{$counterName};
            content: $beforeLabel counter(#{$counterName}) $afterLabel;
            move-to: listBucket;
          }
          &:deferred {
            content: pending(listBucket) content();
          }
        }
      }
```
The variable `$name` have to be one word string like `abstract` or `stepwise` because we are using it to create the names of classes of some containers. So maybe I should add this variable to config? 
Then it will look like that:
```
$Config_CustomList: (
  (selector: '[data-type="abstract"] ul', name: "abstract", beforeLabel: counter(chapter) "." counter(section) ".", afterLabel: ". "),
);
```

**Comment by tomjw64** [comment]
@wilkus27 Really great thoughts. I think that we should go with the `selector` + `name` keys, so that:

1. All calls to this mixin look the same (i.e. less logical branching)
2. The arguments are easier to validate, since they would not be optional (right now use of `className` and `dataTypeName` must be included XOR to work as expected)
3. The name in the selector and class name we give to the baked content can differ if we so choose

Nice work reducing code duplication, by the way!

**Comment by wilkus27** [comment]
@brittany-johnson @tomjw64 thank you for your kind words! :) 

In 7a73e94 I modified mixin and I added new keys to `$Config_CustomList` in **Chemistry** and **Dev-math** (and of course in **Calculus** ).

I'm wondering about release flag. If I want to enable in this PR all of those changes only for **Calculus** I have to create separate mixin, because earlier `mixin modify_lists` was included in generator file in `:pass(10)`.  But I had to move it to `:pass(9)`, because in **Calculus** in `beforeLabel` I'm using counters (`counter(chapter).counter(section)`) and they don't work in `:pass(10)`. So this change causes differences in output files for **Chemistry** and **Dev-math**.

So, should I do this or I can live this as-is? Or maybe I should create a release flag and enable it for all of three books (chemistry, dev-math,calculus)?

**Comment by tomjw64** [comment]
@wilkus27 Since this change is for Calculus, go ahead and make a release flag for this and enable it for all the books except Chemistry and Dev-Math. This will isolate our change but prevent us from doing meaningless rollout in the future.

Just to tack on one more thing: Be sure you validate the type on `$selector`

**Comment by wilkus27** [comment]
Thank you! :)

**Pull request merged**
